version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  dialect = "typescript"
  module_system = "es-modules"
  environment = [
    "nodejs",
    "browser"
  ]
  plugins = ["react"]
  skip_doc_coverage = [
    "function-declaration",
    "function-expression",
    "arrow-function-expression"
  ]

  [[analyzers.meta.exclude_rules]]
  code = "JS-0417"

[[analyzers]]
name = "test-coverage"
enabled = false

[[transformers]]
name = "prettier"
enabled = true
